name: Project Submission
description: "Add your project here to participate and win prizes!"
title: "Project: <short description>"
body:
  - type: input
    id: name
    attributes:
      label: Project Name
      description: Name of your project
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a short description of your submission. Who can benefit from the solution?
    validations:
      required: true
  - type: markdown
    attributes:
       value: "## Technical Category"
  - type: dropdown
    id: category_build
    attributes:
      label: Build
      description: Does your project align with the Build category?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: dropdown
    id: category_train
    attributes:
      label: Train
      description: Does your project align with the Train category?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: dropdown
    id: category_analyze
    attributes:
      label: Analyze
      description: Does your project align with the Analyze category?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Challenge Topic / Topic Category
      description: What topic category does your submission align with.
      options:
        - label: Customized Information Extraction
          required: false
        - label: Education
          required: false
        - label: Enhancing Accessibility in Healthcare Through AI
          required: false
        - label: Mitigating Natural Disasters in a Changing Climate
          required: false
        - label: Reducing Food Waste Through AI-Powered Innovation
          required: false
        - label: other - World Issues
          required: false
        - label: other - Open-Source
          required: false
        - label: other - Scientific Computing
          required: false
        - label: other
          required: false
  - type: input
    id: url_repo
    attributes:
      label: Project Repository URL
      description: URL of the GitHub repo with your project
    validations:
      required: true
  - type: input
    id: url_endpoint
    attributes:
      label: Deployed Endpoint URL
      description: URL of a deployed endpoint (if it can be publicly shared, not for private data)
    validations:
      required: false
  - type: input
    id: video
    attributes:
      label: Project Video File (not folder) Link (ensure viewer access)
      description: A short demo video of your project
    validations:
      required: true
  - type: input
    id: teammembers
    attributes:
      label: Team Members
      description: Comma-separated list of GitHub users who worked on this project
    validations:
      required: true